name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 20

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [22, 24]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: docker
        push: true
        build-args: |
          NODE_VERSION=${{ env.NODE_VERSION }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-tools:${{ env.NODE_VERSION }}
